const answers = [
    { id: 1, en: "Shake me!", ua: "Трухани мене!" },
    { id: 2, en: "Yes", ua: "Так" },
    { id: 3, en: "No", ua: "Ні" },
    { id: 4, en: "Maybe", ua: "Можливо" },
    { id: 5, en: "Ask again later", ua: "Подумай пізніше" },
    { id: 6, en: "Definitely", ua: "Точно" },
    { id: 7, en: "I don't think so", ua: "Не можу побачити" },
    { id: 8, en: "Absolutely", ua: "Абсолютно" },
    { id: 9, en: "Not sure", ua: "Не впевнений" },
    { id: 10, en: "Try again", ua: "Спробуй знову" },
    { id: 11, en: "Very likely", ua: "Дуже ймовірно" },
    { id: 12, en: "Unlikely", ua: "Малоймовірно" },
    { id: 13, en: "Ask someone else", ua: "Запитай когось іншого" },
    { id: 14, en: "Certainly", ua: "Безсумнівно" },
    { id: 15, en: "Doubtful", ua: "Сумнівно" },
    { id: 16, en: "Yes, in due time", ua: "Так, в свій час" },
    { id: 17, en: "Cannot predict now", ua: "Не можу передбачити зараз" },
    { id: 18, en: "Focus and ask again", ua: "Зосередься та запитай знову" },
    { id: 19, en: "Outlook good", ua: "Прогноз добрий" },
    { id: 20, en: "Outlook not so good", ua: "Прогноз не дуже добрий" },
    { id: 21, en: "Yes, but be cautious", ua: "Так, але будь обережним" },
    { id: 22, en: "Don't believe in \"magical\" balls", ua: "Не вірь \"магічним\" кулям" },
];

export default answers;