const answers = [
    { id: 1, en: "Shake me!", ua: "Трухани мене!" },
    { id: 2, en: "Yes", ua: "Так" },
    { id: 3, en: "No", ua: "Ні" },
    { id: 4, en: "Maybe", ua: "Можливо" },
    { id: 5, en: "Ask again later", ua: "Подумай пізніше" },
    { id: 6, en: "Definitely", ua: "Точно" },
    { id: 7, en: "I don't think so", ua: "Не можу побачити" },
    { id: 8, en: "Absolutely", ua: "Абсолютно" },
    { id: 9, en: "Not sure", ua: "Не впевнений" },
    { id: 10, en: "Try again", ua: "Спробуй знову" },
    { id: 11, en: "Very likely", ua: "Дуже ймовірно" },
    { id: 12, en: "Unlikely", ua: "Малоймовірно" },
    { id: 13, en: "Ask someone else", ua: "Запитай когось іншого" },
    { id: 14, en: "Certainly", ua: "Безсумнівно" },
    { id: 15, en: "Doubtful", ua: "Сумнівно" },
    { id: 16, en: "Yes, in due time", ua: "Так, в свій час" },
    { id: 17, en: "Cannot predict now", ua: "Не можу передбачити зараз" },
    { id: 18, en: "Focus and ask again", ua: "Зосередься та запитай знову" },
    { id: 19, en: "Outlook good", ua: "Прогноз добрий" },
    { id: 20, en: "Outlook not so good", ua: "Прогноз не дуже добрий" },
    { id: 21, en: "Yes, but be cautious", ua: "Так, але будь обережним" },
    { id: 22, en: "Don't believe in \"magical\" balls.", ua: "Не вірь \"магічним\" кулям." },
    { id: 23, en: "Yes, but who knows?", ua: "Так, але хто знає?" },
    { id: 24, en: "No, and does it matter?", ua: "Ні, і хіба це важливо?" },
    { id: 25, en: "Maybe, maybe not.", ua: "Можливо, можливо ні." },
    { id: 26, en: "Ask again later. Or don't.", ua: "Запитай пізніше. Або не запитуй." },
    { id: 27, en: "Definitely. Or not.", ua: "Точно. Або ні." },
    { id: 28, en: "I don't think so, but who am I to judge?", ua: "Не думаю, але я лише куля" },
    { id: 29, en: "Try again. Or just give up.", ua: "Спробуй знову. Або просто здавайся." },
    { id: 30, en: "Very likely, but don't get your hopes up.", ua: "Дуже ймовірно, але не надто сподівайся." },
    { id: 31, en: "Unlikely, but stranger things have happened.", ua: "Малоймовірно, але і дивніші речі траплялися." },
    { id: 32, en: "Certainly, if that makes you feel better.", ua: "Безсумнівно, якщо тобі від цього стане краще." },
    { id: 33, en: "Doubtful, but who knows?", ua: "Сумнівно, але хто знає?" },
    { id: 34, en: "Yes, in due time. Maybe.", ua: "Так, в свій час. Можливо." },
    { id: 35, en: "Cannot predict now. Maybe never.", ua: "Не можу передбачити зараз. Можливо, ніколи." },
    { id: 36, en: "Focus and ask again. If you must.", ua: "Зосередься та запитай знову. Якщо вже дуже треба." },
    { id: 37, en: "Outlook good, but who really knows?", ua: "Прогноз добрий, але хто насправді знає?" },
    { id: 38, en: "Outlook not so good. But hey, life.", ua: "Прогноз не дуже добрий. Але таке життя." },
    { id: 39, en: "Don't believe in \"magical\" balls. Seriously.", ua: "Не вірь \"магічним\" кулям. Серйозно." },   
    { id: 40, en: "Why bother? You won't like the answer.", ua: "Навіщо турбуватися? Тобі не сподобається відповідь." },
    { id: 41, en: "Dream on, it's free.", ua: "Мрій далі, це безкоштовно." },
    { id: 42, en: "Not in this lifetime, buddy.", ua: "Не в цьому житті, друже." },
    { id: 43, en: "Don't count on it. Seriously.", ua: "Не розраховуй на це. Серйозно." },
    { id: 44, en: "Fat chance. Really fat.", ua: "Ні найменшого шансу. Дуже ні." },
    { id: 45, en: "In your dreams, and even there it's a stretch.", ua: "У твоїх мріях, і навіть там це сумнівно." },
    { id: 46, en: "Yeah, right. And pigs might fly.", ua: "Ага, звичайно. І свині полетять." },
    { id: 47, en: "Not gonna happen. Keep waiting.", ua: "Не станеться. Чекай далі." },
    { id: 48, en: "As if. Nice try, though.", ua: "Ніби як. Хороша спроба, втім." },
    { id: 49, en: "Better luck next time. Or not.", ua: "Краще пощастить наступного разу. Або ні." },
    { id: 50, en: "Keep dreaming. It's cute.", ua: "Продовжуй мріяти. Це мило." },
];



export default answers;